# -*- coding: utf-8 -*-
"""01_preprocessing_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U_jHHffGcgaPqoFMIOi9PRdhzGkx0B65
"""

# DATA PREPROCESSING
# Insurance Fraud Detection & Claim Severity Decision Support System

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")
sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (8, 5)

df = pd.read_csv("/content/archive.zip")  #load dataset

print("Shape of dataset (rows, columns):", df.shape)
df.head()

"""The dataset has 1000 rows and 40 columns"""

df.info()

# Identifying junk columns
# pandas creates an extra unnamed column in .csv files ('_c39').

print("Missing values in '_c39':", df["_c39"].isnull().sum(), "out of", len(df))

df = df.drop(columns=["_c39"])
print("Column dropped. New shape:", df.shape)

# replace "?" placeholder with missing values

df = df.replace("?", np.nan)

# count missing values
missing = df.isnull().sum()
missing = missing[missing > 0].sort_values(ascending=False)
missing_pct = (missing / len(df) * 100).round(2)

missing_summary = pd.DataFrame({"missing_count": missing, "missing_pct": missing_pct})
print(missing_summary)

"""Four columns have missing values, all categorical:

 property_damage           (36% missing, encoded as "?")


 police_report_available   (34% missing, encoded as "?")


 collision_type            (18% missing, encoded as "?")


 authorities_contacted     (9% missing)

These aren't random data-entry errors, they are STRUCTURALLY missing.
collision_type is NaN mainly when incident_type is "Vehicle Theft" or "Parked Car" (there was no collision, so the field doesn't apply)

authorities_contacted is blank when nobody was called to the scene. This is an important insight for fraud detection(paper[1] specifically discusses handling missing values in imbalanced insurance datasets),
so instead of dropping these rows/columns we will encode "missing" as its own explicit category ("Unknown" / "None") rather than imputing a guessed value.
"""

df["collision_type"] = df["collision_type"].fillna("Unknown")
df["property_damage"] = df["property_damage"].fillna("Unknown")
df["police_report_available"] = df["police_report_available"].fillna("Unknown")
df["authorities_contacted"] = df["authorities_contacted"].fillna("None")

print("Remaining missing values:", df.isnull().sum().sum())

#checking for duplicate rows
duplicate_count = df.duplicated().sum()
print("Number of duplicate rows:", duplicate_count) #duplicate claims can bias the model

# date columns parsing
# policy_bind_date and incident_date are in plain strings.
# convert them to proper datetime objects

df["policy_bind_date"] = pd.to_datetime(
    df["policy_bind_date"], errors="coerce"
)

df["incident_date"] = pd.to_datetime(
    df["incident_date"], errors="coerce"
)
print(df[["policy_bind_date", "incident_date"]].dtypes)

# check target imbalance for target variable
# 'fraud_reported' (Y/N) is our fraud classification target variable

print(df["fraud_reported"].value_counts())
print(df["fraud_reported"].value_counts(normalize=True).round(3) * 100)

sns.countplot(data=df, x="fraud_reported", hue="fraud_reported",
              palette={"Y": "#d62728", "N": "#2ca02c"}, legend=False)
plt.title("Fraud vs Legitimate Claims (Class Distribution)")
plt.xlabel("Fraud Reported")
plt.ylabel("Number of Claims")
plt.tight_layout()
plt.savefig("plots  01_target_class_balance.png", dpi=120)
plt.show()

"""Roughly 75% legitimate vs 25% fraud: this is a CLASS-IMBALANCED problem.
Paper [1] specifically addresses this issue. It matters because a naive model can score 75% accuracy just by predicting "not fraud" for everyone, while being
completely useless. This justifies (for later modeling steps) techniques like SMOTE, class-weighting, or F1/AUC-based evaluation instead of plain accuracy[1].
"""

df.to_csv('processed_insurance_claims.csv', index=False)
print('DataFrame saved to processed_insurance_claims.csv')
